import { useState, useEffect } from 'react';
import Head from 'next/head';

import PageTabs from '../components/PageTabs';
import styles from '../styles/About.module.css';


export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    fetch('https://www.zesty.io/-/instant/7-e93178-vqvclg.json')
      .then((response) => {
        if (response.status < 400) return response.json();
        else throw new Error('Failed to connect');
      })
      .then((responseData) => {
        setData(responseData.data[0].content.page_content);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PageTabs />
        <div className={styles.content} dangerouslySetInnerHTML={{ __html: data }}>
        </div>
      </main>
    </div>
  )
}
