import { useState, useEffect } from 'react';
import Head from 'next/head';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';

import PageTabs from '../components/PageTabs';
import styles from '../styles/Home.module.css';


export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    fetch('https://www.zesty.io/-/gql/platform_section.json')
      .then((response) => {
        if (response.status < 400) return response.json();
        else throw new Error('Failed to connect');
      })
      .then((responseData) => {
        setData(responseData);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PageTabs />
        <div className={styles.cards_container}>
          {data
            .sort((curr, next) => +curr.sort_order - +next.sort_order)
            .map((item) => (
            <Card raised className={styles.card} key={item.title}>
              <CardContent>
                <Typography variant="h4" component="h1">{item.title}</Typography>
                <Typography variant="body2" component="div" dangerouslySetInnerHTML={{ __html: item.text_content || item.media_content }} />
              </CardContent>
            </Card>
          ))}
        </div>
      </main>
    </div>
  )
}
